name: Publish Docker image
 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'Dockerfile'
    - '.github/workflows/publish-docker-image.yml'
  schedule:
    # Monday at 3:00 AM UTC
    - cron: '0 3 * * 1'

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Generate image ID and version
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/rcs-dsri-nvidia-driver-coreos
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest-scos4.18
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Cache: https://docs.docker.com/build/ci/github-actions/cache/#github-cache
      - name: Build and publish main latest Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          pull: true
          push: true
          tags: ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
